FROM fabianacero/centos-php54:decanet
ADD ./dockerDecanet/httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
RUN mkdir /var/www/html/decanet
# DIRECTORIO TEMPORALES
RUN mkdir -p /var/www/files/web/file
RUN chgrp apache /var/&&chgrp apache /var/www/&&chgrp apache /var/www/files/&&chgrp apache /var/www/files/web/&&chgrp apache /var/www/files/web/file
RUN chmod 775 /var/&&chmod 775 /var/www/&&chmod 775 /var/www/files/&&chmod 775 /var/www/files/web/&&chmod 775 /var/www/files/web/file
# DIRECTORIO DE LOGS
RUN mkdir -p /var/log/httpd/logAplicacion
RUN chgrp apache /var/log/&&chgrp apache /var/log/httpd/&&chgrp apache /var/log/httpd/logAplicacion/
RUN chmod 775 /var/log/&&chmod 775 /var/log/httpd/&&chmod 775 /var/log/httpd/logAplicacion/
RUN mkdir -p /etc/httpd/ssl
ADD ./securep.decameron.com.crt /etc/httpd/ssl/securep.decameron.com.crt
ADD ./securep.decameron.com.key /etc/httpd/ssl/securep.decameron.com.key
EXPOSE 80
CMD ["/bin/bash"]
