FROM jgomez17/centos-php54:secure
ADD ./dockerSecure/httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
RUN mkdir /var/www/html/secure-web-gds
RUN mkdir /var/www/html/amadeusdecameron
RUN mkdir /var/www/html/pnp-webservice
EXPOSE 80
CMD ["/bin/bash"]
